### ISSUE TITLE
Use $npm_package variables

### ISSUE THREAD

**Issue by g-div** [h2non/nar#115]
```nar``` is a really great project and I would like to use it to deploy my apps, but I'm experiencing a problem with my ```package.json```.

I use to write my ```package.json``` like this:

```
{
  "name": "testpackage",
  "version": "0.0.1",
  "description": "A test package",
  "main": "index.js",
  "archive": {
    "dependencies": true,
    "devDependencies": false,
    "globalDependencies": [
      "npm"
    ]
  },
  "scripts": {
    "start": "node $npm_package_main",
    "build": "nar create --executable"
  },
  "devDependencies": {
    "nar": "^0.3.20"
  }
}
```

```npm start``` works, but if I create an executable with ```nar create --executable``` and run it, I will get the following error:
```
Extracting files...
Extract [global-dependency] npm
Extract [package] testpackage
Running testpackage-0.0.1.nar
Run [start]: /usr/bin/env bash ~/testpackage/.nar/nar/scripts/node.sh $npm_package_main
Running application...
> module.js:338
>     throw err;
>     ^
> 
> Error: Cannot find module '/tmp/nar-testpackage-0.0.1-1446201800070/$npm_package_main'
>     at Function.Module._resolveFilename (module.js:336:15)
>     at Function.Module._load (module.js:286:25)
>     at Function.Module.runMain (module.js:475:10)
>     at startup (node.js:118:18)
>     at node.js:952:3
Error: Command failed with exit code: 1
```

The start script isn't able to recognize [```package.json``` variables](https://docs.npmjs.com/misc/scripts#package-json-vars).
Is there a way to achieve this ?

**Comment by h2non** [comment]
Unfortunately `npm` built-in variables are not supported, but I would like to support it soon.

In the meantime, you can explicitly pass the version as environment variable, but you have to usea sightly different notation:
```json
 "scripts": {
    "start": "node ${VERSION}"
 }
```

Or alternatively, you can run the script via `npm` (as you're embedding it):
```json
 "scripts": {
    "start": "npm run boot",
    "boot": "node $npm_package_main"
 }
```

**Comment by g-div** [comment]
Thanks. I've wrapped my start script as in your second example and it works perfectly. 
It would still be useful to have access to ```npm``` variables.

**Comment by h2non** [comment]
Great! I've created another issue as feature request for `npm` variables. See #116

**Comment by mend3** [comment]
> Unfortunately `npm` built-in variables are not supported, but I would like to support it soon.
> 
> In the meantime, you can explicitly pass the version as environment variable, but you have to use a sightly different notation:
> 
> ```json
>  "scripts": {
>     "start": "node ${VERSION}"
>  }
> ```
> 
> Or alternatively, you can run the script via `npm` (as you're embedding it):
> 
> ```json
>  "scripts": {
>     "start": "npm run boot",
>     "boot": "node $npm_package_main"
>  }
> ```

I know it's a bit late, but for further Windows devs:

If you're on Windows, you must wrap your npm_package_whatever with %

In the given case, the script

`"boot": "node $npm_package_main"`

 would become:

`"boot": "node %npm_package_main%"`

**Comment by dandv** [comment]
Note that [`$npm_package_*` variables are no longer automatically placed in the environment since NPM v7](https://github.com/npm/rfcs/issues/305).
