### ISSUE TITLE
The published nar module contains nar-0.3.28-darwin-x64.nar

### ISSUE THREAD

**Issue by fred-o** [h2non/nar#127]
When installing nar using npm you also get nar-0.3.28-darwin-x64.nar, which is ~30MB and inflates the size of all generated executables.

**Comment by h2non** [comment]
Damn it! `.npmignore` has a bad glob expression to ignore. Will fix now.

**Comment by h2non** [comment]
Fixed in `0.3.32`. Thanks for reporting.
