### ISSUE TITLE
Include static files in nar acrhive

### ISSUE THREAD

**Issue by crazyquark** [h2non/nar#141]
Hello,

Is there a way to bundle static files(like binaries and such) in a .nar archive?
We need to also bundle some precompiled binaries with our node app.

**Comment by h2non** [comment]
If the pre-compiled binary files are inside a `node_modules` dependency tree, such as `node_modules/mydep/binary` and `mydep` is a dependency defined in `package.json`, `nar` should embed it in the resultant `nar` archive, therefore those files will be added and then extracted properly.
`nar` will add to the archive all the files in `mydep` folder following the glob pattern: `node_modules/mydep/**`

Have you tried creating a `nar` archive with that kind of dependency? 
Worth to mention that binary files are platform specific, so if you're running OSX and then you want to run the `nar` executable under Linux, it won't work.

**Comment by crazyquark** [comment]
Unfortunately this is not a dependency, but an external program that needs to be bundled with the app. If I put it in node_modules then npm install will fail...

**Comment by h2non** [comment]
Then add those files in your package tree or declare a node dependency containing it.

**Comment by crazyquark** [comment]
Yup, that's what I did, I packaged them as a node module.
Thanks.
