### ISSUE TITLE
Cannot find module unicode

### ISSUE THREAD

**Issue by mostr** [h2non/nar#142]
I'm having https://github.com/dodo/node-slug as project dependency in `package.json`. It requires `unicode` that gets installed too. App is working fine, but I'm getting this error below when packaging it with NAR
```
$ nar create -o app
Creating archive...
Error: Cannot find module 'unicode' from '/Users/mostr/app/node_modules/slug'
```

Any hints?

**Comment by h2non** [comment]
require.resolve is not able to resolve that package. A main entry should be defined in package.json, or we can add an exception in resolve-tree package for it.

**Comment by zaventh** [comment]
I'm running in to a similar problem.

> Error: Cannot find module 'timers-ext' from '[redacted]/node_modules/[redacted]/node_modules/memoizee'

Even if I `npm i timers-ext --save` from my app, I get the same error. I looked at resolve-tree, but I am not sure how to resolve really.

**Comment by h2non** [comment]
@zaventh Same problem: `timers-ext` has no explicit resolution module in `package.json`: 
https://github.com/medikoo/timers-ext/blob/master/package.json

I can add an exception in `resolve-tree`.

**Comment by h2non** [comment]
This should be fixed now. Feel free to update `nar`:
```bash
npm update -g --force nar
```
