### ISSUE TITLE
does nar support windows and OSx ?

### ISSUE THREAD

**Issue by sequoiar** [h2non/nar#85]
Like nar.exe on widnows, and nar.app on OSx

**Comment by lygstate** [comment]
It's annoy when developing tings under win32, can you add a fake nar support under win32?
I means can run like POSIX platform, but do not do real package.

**Comment by h2non** [comment]
You can create `nar` standard archives (not executables) for any OS, however executables are platform specific and it's only supported POSIX.

Alternatively, under Windows you could use [Cygwin](https://www.cygwin.com/)
